name: bookquotes
description: "Book quotes app"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.5.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  dartz: ^0.10.1
  equatable: ^2.0.7
  internet_connection_checker: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true


